sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
rvm:
  - 2.1.7
before_install:
  - npm install -g grunt-cli
  - gem update --system && gem install scss_lint -v 0.44.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - jason@project41innovations.com
